### ISSUE TITLE
I'm on the last ember, ember-cli, ember-data STABLE (not beta), with 5.2.2 I got an error in ember s.

### ISSUE THREAD

**Issue by johnunclesam** [babel/ember-cli-babel#109]
I'm on the last ember, ember-cli, ember-data STABLE (not beta), with 5.2.2 I got a big error in `ember s` today.

**Comment by rwjblue** [comment]
Can you share the error you received?

**Comment by johnunclesam** [comment]
Yes, sorry, I forgot.

```
$ ember s
WARNING: Node v7.5.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
File: myapp/adapters/application.js
The Broccoli Plugin: [broccoli-persistent-filter:Babel > [Babel: myapp]: Babel: myapp] failed with:
ReferenceError: [BABEL] myapp/adapters/application.js: Unknown option: direct.annotation
    at Logger.error (C:\myapp\node_modules\babel-core\lib\transformation\file\logger.js:58:11)
    at OptionManager.mergeOptions (C:\myapp\node_modules\babel-core\lib\transformation\file\options\option-manager.js:126:29)
    at OptionManager.init (C:\myapp\node_modules\babel-core\lib\transformation\file\options\option-manager.js:216:10)
    at File.initOptions (C:\myapp\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (C:\myapp\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (C:\myapp\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at Babel.transform (C:\myapp\node_modules\broccoli-babel-transpiler\index.js:105:21)
    at Babel.processString (C:\myapp\node_modules\broccoli-babel-transpiler\index.js:204:25)
    at Promise.then.result.output (C:\myapp\node_modules\broccoli-persistent-filter\lib\strategies\persistent.js:41:23)
    at initializePromise (C:\myapp\node_modules\rsvp\dist\rsvp.js:588:5)

The broccoli plugin was instantiated at:
    at Babel.Plugin (C:\myapp\node_modules\broccoli-plugin\index.js:7:31)
    at Babel.Filter [as constructor] (C:\myapp\node_modules\broccoli-persistent-filter\index.js:62:10)
    at new Babel (C:\myapp\node_modules\broccoli-babel-transpiler\index.js:35:10)
    at Babel (C:\myapp\node_modules\broccoli-babel-transpiler\index.js:30:12)
    at Object.toTree (C:\myapp\node_modules\ember-cli-babel\index.js:30:52)
    at C:\myapp\node_modules\ember-cli-preprocess-registry\preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (C:\myapp\node_modules\ember-cli-preprocess-registry\preprocessors.js:178:11)
    at module.exports.preprocessJs (C:\myapp\node_modules\ember-cli-preprocess-registry\preprocessors.js:171:10)
    at EmberApp.appAndDependencies (C:\myapp\node_modules\ember-cli\lib\broccoli\ember-app.js:1115:25)
```

**Comment by rwjblue** [comment]
Thanks for reporting! Seems related to https://github.com/babel/ember-cli-babel/pull/108, but I'm not quite sure what is wrong just yet.

**Comment by vvainio** [comment]
I also bumped into this at work, forcing `ember-cli-babel` to `5.2.1` through `package.json` fixed the issue for now. The log output is exactly the same as above.

**Comment by rwjblue** [comment]
Hmm.  I cannot get this error to trigger on a fresh app (just tried with cleared node module caches and everything).

Can one of y'all run the following:

```
npm ls ember-cli-babel
```

and:

```
npm ls broccoli-babel-transpiler
```

**Comment by vvainio** [comment]
Thanks for giving it a spin - looks like Yarn was the culprit on my end.

Installing dependencies via npm resulted in `broccoli-babel-transpiler@5.6.2` whereas Yarn resolved to `broccoli-babel-transpiler@5.6.1`. It's been a few months since I tried using Yarn, and the old lock file was still in place. Running `yarn upgrade` fixed the issue on my end ✌️ 

@johnunclesam could still confirm whether he's having a similar case.

**Comment by rwjblue** [comment]
Ahh, I see.  I can change our package.json to indicate that as the minimum version (which would help yarn figure things out I believe)...

**Comment by johnunclesam** [comment]
Fixed, thanks.
