### ISSUE TITLE
The Broccoli Plugin: [broccoli-persistent-filter:Babel] failed with decorators

### ISSUE THREAD

**Issue by GCorbel** [babel/ember-cli-babel#141]
Hi,

I'm trying to use decorators with ember-cli-babel 6.0.0 but I have this error : 

```
The Broccoli Plugin: [broccoli-persistent-filter:Babel] failed with:
SyntaxError: tiny/components/kh-health-card-field.js: Unexpected token (10:2)
   8 |   classNameBindings: ['customField.property'],
   9 |
> 10 |   @computed('customField.property')
     |   ^
  11 |   details() {
  12 |     const property = this.get('customField.property');
  13 |     const type = this.get('customField.type');
    at Parser.pp$5.raise (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:4333:13)
    at Parser.pp.unexpected (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:1705:8)
    at Parser.pp$1.parseDecorator (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:1885:10)
    at Parser.pp$3.parseObj (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3887:28)
    at Parser.pp$3.parseExprAtom (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3639:19)
    at Parser.pp$3.parseExprSubscripts (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3414:19)
    at Parser.pp$3.parseMaybeUnary (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3394:19)
    at Parser.pp$3.parseExprOps (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3324:19)
    at Parser.pp$3.parseMaybeConditional (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3301:19)
    at Parser.pp$3.parseMaybeAssign (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3264:19)
    at Parser.pp$3.parseExprListItem (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:4190:16)
    at Parser.pp$3.parseCallExpressionArguments (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3493:20)
    at Parser.pp$3.parseSubscripts (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3453:31)
    at Parser.pp$3.parseExprSubscripts (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3424:15)
    at Parser.pp$3.parseMaybeUnary (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3394:19)
    at Parser.pp$3.parseExprOps (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3324:19)
    at Parser.pp$3.parseMaybeConditional (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3301:19)
    at Parser.pp$3.parseMaybeAssign (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3264:19)
    at Parser.pp$1.parseExport (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:2571:19)
    at Parser.pp$1.parseStatement (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:1830:74)
    at Parser.pp$1.parseBlockBody (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:2212:21)
    at Parser.pp$1.parseTopLevel (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:1723:8)

The broccoli plugin was instantiated at:
    at Babel.Plugin (/home/dougui/workspace/tiny/frontend/node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (/home/dougui/workspace/tiny/frontend/node_modules/broccoli-persistent-filter/index.js:62:10)
    at new Babel (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:35:10)
    at Babel (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:30:12)
    at Class.transpileTree (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli-babel/index.js:38:48)
    at Object.toTree (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli-babel/index.js:45:30)
    at /home/dougui/workspace/tiny/frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at module.exports.preprocessJs (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:171:10)
    at EmberApp.appAndDependencies (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1110:27)
    at EmberApp.javascript (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1227:30)
    at EmberApp.toArray (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1664:12)
    at EmberApp.toTree (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1686:38)
    at module.exports (/home/dougui/workspace/tiny/frontend/ember-cli-build.js:25:14)
    at Builder.setupBroccoliBuilder (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/lib/models/builder.js:30:10)
    at BuildTask.run (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/lib/models/command.js:242:46)
    at tryCatch (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:553:13)
    at /home/dougui/workspace/tiny/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:628:16
```
Here is my `ember-cli-build.js : 

```
/* eslint-env node */
const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    babel: {
      optional: ['es7.decorators']
    }
  });

  return app.toTree();
};
```

The optional value doesn't make a difference. It worked with ember-cli-babel 5.

Did I miss something?

**Comment by stefanpenner** [comment]
Unfortunately babel changed the plugin API between 5 and 6.  Closing this in-favor of your issue on ember-computed-decorators https://github.com/rwjblue/ember-computed-decorators/issues/90
