### ISSUE TITLE
Polyfill not working for IE10

### ISSUE THREAD

**Issue by badazz91** [babel/ember-cli-babel#162]
Hey guys,

I'm using ```ember 2.14.0```.
For some reasons when starting the app with IE10 following error occurs:

```
TypeError: Object doesn't support property or method 'resolve'
   at Anonymous function (http://<ip>/assets/vendor.js:75866:9)
   at tryCatch (http://<ip>/assets/vendor.js:75103:7)
   at invokeCallback (http://<ip>/assets/vendor.js:75118:7)
   at publish (http://<ip>/assets/vendor.js:75086:9)
   at Anonymous function (http://<ip>/assets/vendor.js:65900:9)
   at invokeWithOnError (http://<ip>/assets/vendor.js:31244:21)
   at flush (http://<ip>/assets/vendor.js:31130:21)
   at flush (http://<ip>/assets/vendor.js:31293:21)
   at end (http://<ip>/assets/vendor.js:31372:17)
   at run (http://<ip>/assets/vendor.js:31451:21) 
```

Running the same app with IE11, everything is fine.

I included 
```
 'ember-cli-babel': {
    includePolyfill: true
  }
```
in my ember-cli-build file.

After some searching I suspect that it has something to do with polyfilling ES6 methods. But I am not sure.
Any ideas on this?

**Comment by badazz91** [comment]
It seems to be related to the ```finally``` block of a ajax promise. Removing ``` finally ``` solved it.

**Comment by joankaradimov** [comment]
I am experiencing an identical problem. Getting rid of the calls to `finally` solved it.

**Comment by byrnedo** [comment]
I'm also getting this, is there anything I can do to get this to work? I have `finally` all over the shop.

**Comment by byrnedo** [comment]
Bump

**Comment by rwjblue** [comment]
Is the polyfill supposed to support `.finally`?  AFAIK, it hasn't landed in ES yet ([checking the list of active proposals](https://github.com/tc39/proposals#active-proposals) shows it is only Stage 3).

**Comment by rwjblue** [comment]
Looks like core-js got `Promise.prototype.finally` support in https://github.com/zloirock/core-js/commit/ed59a9c0822eb1fa3509e06f996f424d8392d0a9 (which was published in 2.5.0).  What version do you have?

**Comment by byrnedo** [comment]
I'm not sure what's supported or not but I was under the impression that ember cli supported promise.finally some way or another. 

The ember-cli-babel version I have is 5.2.4. But do you mean another version?

**Comment by byrnedo** [comment]
if it's core's version: 
```
├─┬ babel-plugin-transform-object-rest-spread@6.23.0
│ └─┬ babel-runtime@6.25.0
│   └── core-js@2.5.0 
├─┬ ember-cli-content-security-policy@0.6.0
│ └─┬ ember-cli-babel@5.2.4
│   └─┬ broccoli-babel-transpiler@5.7.2
│     └─┬ babel-core@5.8.38
│       └── core-js@1.2.7 
├─┬ ember-cli-ifa@0.3.0
│ └─┬ ember-cli-babel@5.2.4
│   └─┬ broccoli-babel-transpiler@5.7.2
│     └─┬ babel-core@5.8.38
│       └── core-js@1.2.7 
├─┬ ember-cli-nouislider@0.11.0
│ └─┬ ember-cli-babel@5.2.4
│   └─┬ broccoli-babel-transpiler@5.7.2
│     └─┬ babel-core@5.8.38
│       └── core-js@1.2.7 
├─┬ ember-cli-pickadate@1.3.6
│ ├─┬ ember-cli-babel@5.2.4
│ │ └─┬ broccoli-babel-transpiler@5.7.2
│ │   └─┬ babel-core@5.8.38
│ │     └── core-js@1.2.7 
│ └─┬ ember-get-config@0.0.3
│   └─┬ ember-cli-babel@5.2.4
│     └─┬ broccoli-babel-transpiler@5.7.2
│       └─┬ babel-core@5.8.38
│         └── core-js@1.2.7 
├─┬ ember-cli-sass@5.6.0
│ └─┬ ember-cli-babel@5.1.10
│   └─┬ broccoli-babel-transpiler@5.7.2
│     └─┬ babel-core@5.8.38
│       └── core-js@1.2.7 
├─┬ ember-cli-test-loader@1.1.1
│ └─┬ ember-cli-babel@5.2.4
│   └─┬ broccoli-babel-transpiler@5.7.2
│     └─┬ babel-core@5.8.38
│       └── core-js@1.2.7 
├─┬ ember-cli-textarea-autosize@1.0.1
│ └─┬ ember-cli-babel@5.2.4
│   └─┬ broccoli-babel-transpiler@5.7.2
│     └─┬ babel-core@5.8.38
│       └── core-js@1.2.7 
├─┬ ember-hotjar@0.0.2
│ └─┬ ember-cli-babel@5.2.4
│   └─┬ broccoli-babel-transpiler@5.7.2
│     └─┬ babel-core@5.8.38
│       └── core-js@1.2.7 
├─┬ ember-i18n@5.0.2
│ ├─┬ ember-cli-babel@5.2.4
│ │ └─┬ broccoli-babel-transpiler@5.7.2
│ │   └─┬ babel-core@5.8.38
│ │     └── core-js@1.2.7 
│ └─┬ ember-getowner-polyfill@1.2.5
│   └─┬ ember-cli-babel@5.2.4
│     └─┬ broccoli-babel-transpiler@5.7.2
│       └─┬ babel-core@5.8.38
│         └── core-js@1.2.7 
├─┬ ember-i18n-inject@0.0.2
│ └─┬ ember-cli-babel@5.2.4
│   └─┬ broccoli-babel-transpiler@5.7.2
│     └─┬ babel-core@5.8.38
│       └── core-js@1.2.7 
├─┬ ember-leaflet@2.2.7
│ ├─┬ ember-cli-babel@5.2.4
│ │ └─┬ broccoli-babel-transpiler@5.7.2
│ │   └─┬ babel-core@5.8.38
│ │     └── core-js@1.2.7 
│ └─┬ ember-invoke-action@1.2.0
│   └─┬ ember-cli-babel@5.2.4
│     └─┬ broccoli-babel-transpiler@5.7.2
│       └─┬ babel-core@5.8.38
│         └── core-js@1.2.7 
├─┬ ember-moment@7.4.1
│ └─┬ ember-macro-helpers@0.15.1
│   └─┬ ember-weakmap@2.0.0
│     └─┬ ember-cli-babel@5.2.4
│       └─┬ broccoli-babel-transpiler@5.7.2
│         └─┬ babel-core@5.8.38
│           └── core-js@1.2.7 
├─┬ ember-promise-helpers@1.0.3
│ └─┬ ember-cli-babel@5.2.4
│   └─┬ broccoli-babel-transpiler@5.7.2
│     └─┬ babel-core@5.8.38
│       └── core-js@1.2.7 
├─┬ ember-tether@0.3.1
│ └─┬ ember-cli-babel@5.2.4
│   └─┬ broccoli-babel-transpiler@5.7.2
│     └─┬ babel-core@5.8.38
│       └── core-js@1.2.7 
├─┬ ember-tooltips@2.8.0
│ ├─┬ ember-cli-babel@5.2.4
│ │ └─┬ broccoli-babel-transpiler@5.7.2
│ │   └─┬ babel-core@5.8.38
│ │     └── core-js@1.2.7 
│ └─┬ ember-hash-helper-polyfill@0.1.2
│   └─┬ ember-cli-babel@5.2.4
│     └─┬ broccoli-babel-transpiler@5.7.2
│       └─┬ babel-core@5.8.38
│         └── core-js@1.2.7 
├─┬ ember-truth-helpers@1.3.0
│ └─┬ ember-cli-babel@5.2.4
│   └─┬ broccoli-babel-transpiler@5.7.2
│     └─┬ babel-core@5.8.38
│       └── core-js@1.2.7 
└─┬ emberx-file-input@1.1.2
  └─┬ ember-cli-babel@5.2.4
    └─┬ broccoli-babel-transpiler@5.7.2
      └─┬ babel-core@5.8.38
        └── core-js@1.2.7 

```

**Comment by byrnedo** [comment]
@rwjblue is there a next step?

**Comment by rwjblue** [comment]
Sorry for letting this linger, I think at this point IE10 is completely unsupported.
