### ISSUE TITLE
Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null

### ISSUE THREAD

**Issue by lolmaus** [babel/ember-cli-babel#171]
I've got an [app](https://github.com/bread-maker/bread-maker-ember-frontend) that compiles fine.

After I do `yarn upgrade`, it fails to compile with:

```
$ ember t
cleaning up...
Build failed.
The Broccoli Plugin: [BroccoliMergeTrees: Addon#treeFor (ember-moment - addon)] failed with:
TypeError: ember-moment/utils/get-owner.js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null
    at Object.validate (/home/lolmaus/Code/bread-maker/bread-maker-ember-frontend/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/home/lolmaus/Code/bread-maker/bread-maker-ember-frontend/node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (/home/lolmaus/Code/bread-maker/bread-maker-ember-frontend/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath._remove (/home/lolmaus/Code/bread-maker/bread-maker-ember-frontend/node_modules/babel-traverse/lib/path/removal.js:58:10)
    at NodePath.remove (/home/lolmaus/Code/bread-maker/bread-maker-ember-frontend/node_modules/babel-traverse/lib/path/removal.js:30:8)
    at PluginPass.CallExpression (/home/lolmaus/Code/bread-maker/bread-maker-ember-frontend/node_modules/babel-plugin-transform-es2015-modules-amd/lib/index.js:42:12)
    at NodePath._call (/home/lolmaus/Code/bread-maker/bread-maker-ember-frontend/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/lolmaus/Code/bread-maker/bread-maker-ember-frontend/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/lolmaus/Code/bread-maker/bread-maker-ember-frontend/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/home/lolmaus/Code/bread-maker/bread-maker-ember-frontend/node_modules/babel-traverse/lib/context.js:150:16)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/home/lolmaus/Code/bread-maker/bread-maker-ember-frontend/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/home/lolmaus/Code/bread-maker/bread-maker-ember-frontend/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:16:10)
    at Function.BroccoliMergeTrees [as _upstreamMergeTrees] (/home/lolmaus/Code/bread-maker/bread-maker-ember-frontend/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:10:53)
    at mergeTrees (/home/lolmaus/Code/bread-maker/bread-maker-ember-frontend/node_modules/ember-cli/lib/broccoli/merge-trees.js:85:33)
    at Class.treeFor (/home/lolmaus/Code/bread-maker/bread-maker-ember-frontend/node_modules/ember-cli/lib/models/addon.js:521:30)
    at project.addons.map.addon (/home/lolmaus/Code/bread-maker/bread-maker-ember-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:557:22)
    at Array.map (native)
    at EmberApp.addonTreesFor (/home/lolmaus/Code/bread-maker/bread-maker-ember-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:555:32)
    at EmberApp._addonTree (/home/lolmaus/Code/bread-maker/bread-maker-ember-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:956:29)
    at EmberApp._processedExternalTree (/home/lolmaus/Code/bread-maker/bread-maker-ember-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1009:25)
```

I doubt that `ember-moment` is to blame. Looks like the issue is related to Babel.

Please advise.

**Comment by lolmaus** [comment]
Here's the diff of `yarn.lock` before and after `yarn upgrade`: https://gist.github.com/lolmaus/942e8453707a635391f7b75386540df9

**Comment by lolmaus** [comment]
It seems that `ember-moment` *is* responsible after all: https://github.com/stefanpenner/ember-moment/issues/249

**Comment by rwjblue** [comment]
FWIW, the issue and stack trace here is caused by using the global `require` statement. As I mentioned in the issue in ember-moment that particular dynamic require isn't needed here any longer, but for others any others that land here with a similar stack trace that _do_ need a dynamic require you need to `import require from 'require';` to avoid the error. 

The error is caused by the fact that babel@6 generates AMD by transpiling ES modules to CJS _before_ transpiling to AMD format. Unfortunately, this means that any dynamic `require` statements are indistinguishable from ES imports. :sob:
