### ISSUE TITLE
Excluding directories gives 'Unknown option: direct.exclude'

### ISSUE THREAD

**Issue by BlueRaja** [babel/ember-cli-babel#182]
I'm trying to exclude a directory full of large files from being transpiled.  I have this in `ember-cli-build.js`:

```
    babel: {
      optional: ['es7.decorators'],
      exclude: ['tests/mocks'],
    },
```
However, when I run it I see
```
ReferenceError: [BABEL] ember-ajax/-private/promise.js: Unknown option: direct.exclude
    at Logger.error (/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.init (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:216:10)
    at File.initOptions (/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at /node_modules/broccoli-babel-transpiler/lib/parallel-api.js:102:26
    at initializePromise (/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/node_modules/rsvp/dist/rsvp.js:1039:33)
...
The broccoli plugin was instantiated at: 
    at Concat.Plugin (/node_modules/broccoli-plugin/index.js:7:31)
    at new Concat (/node_modules/broccoli-concat/concat.js:38:10)
    at module.exports (/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/node_modules/ember-cli/lib/broccoli/ember-app.js:392:10)
    at EmberApp.emberApp.concatFiles (/node_modules/ember-cli-fastboot/lib/ext/patch-ember-app.js:24:32)
...
```
if I remove the `exlude` option the error goes away.  Am I doing something wrong?

Using the latest version of `babel-runtime` and `ember-cli-babel`; however, `ember-cli` is on 2.11.0

**Comment by rwjblue** [comment]
The latest version of ember-cli-babel does not support `optional` either, I do not believe the functionality you are looking for exists....

**Comment by rwjblue** [comment]
To accomplish your task you would have to split the tree with a few broccoli-funnels (one with include and one with exclude), then only process the tree excludes the files with ember-cli-babel.  It should be possible to do manually, but it will be annoying to write 😝 ...

**Comment by BlueRaja** [comment]
I'm confused; so `exclude` is not an option?  It's part of [the example on the main page](https://github.com/babel/ember-cli-babel), _and_ listed under 'options' on that same page, _and_ listed as an option for [babel-preset-env](https://github.com/babel/babel-preset-env#options)

**Comment by rwjblue** [comment]
`exclude` is an option for ember-cli-babel@6 and babel-preset-env, however it doesn't mean what you are using it for (it means to exclude a given plugin from transpilation, **not** exclude a specific directory from being transpiled).

**Comment by rwjblue** [comment]
> Also optional is working correctly, so I'm not sure what you mean by that.

This is very surprising.  How have you confirmed that it is working correctly?  AFAICT, `optional` may not throw an error, but there is no code in `babel-preset-env` or `ember-cli-babel` that does _anything_ with it...

**Comment by BlueRaja** [comment]
Ah!  That makes sense.

Apparently I should be able to actually do this with `babel.ignore` in `package.json`, but I'm not having luck with that.  I'll look into it some more another time.

**Comment by BlueRaja** [comment]
Also, I can't tell you why `optional` is working, but it most definitely is.  If I remove that line, babel fails with
```
    SyntaxError: /pods/components/shared-presentation/cta-wishlist-button/component.js: Unexpected token (60:4)
     * @return {Null}
     */
    @loading('notClickable')
    buttonClicked() {
    at Parser.pp.raise (/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.parseDecorator (/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:170:10)
    at Parser.pp.parseObj (/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:601:28)
    at Parser.pp.parseExprAtom (/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:392:19)
    ...
```
