### ISSUE TITLE
6.9.0 breaks build

### ISSUE THREAD

**Issue by joshsearles** [babel/ember-cli-babel#188]
6.9.0 breaks and gives this error.

6.8.2 is stable and works fine.

```
Cannot find module 'babel-preset-env/lib/targets-parser'
Error: Cannot find module 'babel-preset-env/lib/targets-parser'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Class._getTargets (/usr/local/src/emberrepo/node_modules/ember-cli-babel/index.js:297:18)
    at Class.isPluginRequired (/usr/local/src/emberrepo/node_modules/ember-cli-babel/index.js:125:24)
    at Class.module.exports.included (/usr/local/src/emberrepo/node_modules/ember-maybe-import-regenerator/index.js:20:42)
    at Class.superWrapper [as included] (/usr/local/src/emberrepo/node_modules/core-object/lib/assign-properties.js:34:20)
    at addons.reduce (/usr/local/src/emberrepo/node_modules/ember-cli/lib/models/addon.js:384:26)
    at Array.reduce (native)
```

**Comment by rwjblue** [comment]
Thanks for reporting!

**Comment by rwjblue** [comment]
This is resolved now, sorry for not closing before.
