### ISSUE TITLE
6.9.1 Breaks build when its part of a nested dependency for exmaple ember-loadsh or ember-ajax

### ISSUE THREAD

**Issue by svkangal** [babel/ember-cli-babel#191]
Seeing this error where the nested 

BuildingInvalid Version: function emberCLIVersion() {
    var gitPath = path.join(__dirname, '..','..','.git');
    var output  = [require('../../package.json').version];

    if (existsSync(gitPath)) {
      var repoInfo = getRepoInfo(gitPath);

      output.push(repoInfo.branch);
      output.push(repoInfo.abbreviatedSha);
    }

    return output.join('-');
  }
TypeError: Invalid Version: function emberCLIVersion() {
    var gitPath = path.join(__dirname, '..','..','.git');
    var output  = [require('../../package.json').version];

    if (existsSync(gitPath)) {
      var repoInfo = getRepoInfo(gitPath);

      output.push(repoInfo.branch);
      output.push(repoInfo.abbreviatedSha);
    }

    return output.join('-');
  }
    at new SemVer (/Users/skangal/audience-insights-ui/node_modules/semver/semver.js:279:11)
    at compare (/Users/skangal/audience-insights-ui/node_modules/semver/semver.js:566:10)
    at Function.gt (/Users/skangal/audience-insights-ui/node_modules/semver/semver.js:595:10)
    at Class._shouldCompileModules (/Users/skangal/audience-insights-ui/node_modules/ember-lodash/node_modules/ember-cli-babel/index.js:343:21)
    at Class._getBabelOptions (/Users/skangal/audience-insights-ui/node_modules/ember-lodash/node_modules/ember-cli-babel/index.js:192:37)
    at Class.buildBabelOptions (/Users/skangal/audience-insights-ui/node_modules/ember-lodash/node_modules/ember-cli-babel/index.js:37:17)
    at Class.transpileTree (/Users/skangal/audience-insights-ui/node_modules/ember-lodash/node_modules/ember-cli-babel/index.js:53:58)
    at Object.toTree (/Users/skangal/audience-insights-ui/node_modules/ember-lodash/node_modules/ember-cli-babel/index.js:62:30)
    at /Users/skangal/audience-insights-ui/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)

**Comment by rwjblue** [comment]
Thanks for reporting! Will get a fix out ASAP!

**Comment by svkangal** [comment]
Thanks @rwjblue

**Comment by rwjblue** [comment]
Fix has been published as v6.9.2, sorry about the issues!

**Comment by svkangal** [comment]
Np at all thanks for fixing quickly
