### ISSUE TITLE
Object Spread Operator Plugin does not work on Version 7+

### ISSUE THREAD

**Issue by Paskalouis** [babel/ember-cli-babel#248]
Hi,

I just upgrade to version 7, and my ember-cli-build.js has this

```javascript
babel: {
      plugins: ['transform-object-rest-spread']
},
```

and I have the plugin installed on package.json
But instead it show this error when I build the app.

```
Build Error (StubGenerator)

Error parsing code while looking for "npm:" imports in file: /home/w3o-paska/workspace/sbiz-payment-devtest/client/tmp/stub_generator-input_base_path-1OrjpvkS.tmp/client/pods/general-payment/checkout/route.js
SyntaxError: Unexpected token (25:33)
    at Parser.pp$4.raise (/home/w3o-paska/workspace/sbiz-payment-devtest/client/node_modules/acorn/dist/acorn.js:2757:13)
    at Parser.pp.unexpected (/home/w3o-paska/workspace/sbiz-payment-devtest/client/node_modules/acorn/dist/acorn.js:647:8)
    at Parser.pp$3.parseIdent (/home/w3o-paska/workspace/sbiz-payment-devtest/client/node_modules/acorn/dist/acorn.js:2712:10)
    at Parser.pp$3.parsePropertyName (/home/w3o-paska/workspace/sbiz-payment-devtest/client/node_modules/acorn/dist/acorn.js:2496:105)
    at Parser.pp$3.parseProperty (/home/w3o-paska/workspace/sbiz-payment-devtest/client/node_modules/acorn/dist/acorn.js:2426:8)
    at Parser.pp$3.parseObj (/home/w3o-paska/workspace/sbiz-payment-devtest/client/node_modules/acorn/dist/acorn.js:2380:23)
    at Parser.pp$3.parseExprAtom (/home/w3o-paska/workspace/sbiz-payment-devtest/client/node_modules/acorn/dist/acorn.js:2179:17)
    at Parser.pp$3.parseExprSubscripts (/home/w3o-paska/workspace/sbiz-payment-devtest/client/node_modules/acorn/dist/acorn.js:2047:19)
    at Parser.pp$3.parseMaybeUnary (/home/w3o-paska/workspace/sbiz-payment-devtest/client/node_modules/acorn/dist/acorn.js:2024:17)
    at Parser.pp$3.parseExprOps (/home/w3o-paska/workspace/sbiz-payment-devtest/client/node_modules/acorn/dist/acorn.js:1966:19)


Stack Trace and Error Report: /tmp/error.dump.3607a46632af708cfc87f493a638308b.log
```

I revert to version 6.6.0, and it is working normally.
Is this a new bug on version 7 ?

Thank you !

**Comment by rwjblue** [comment]
You need to update the Babel plugin you are using for rest spread to the one provided by Babel. Specifically it should be within the `@babel` scope...

**Comment by rwjblue** [comment]
Also, that error seems to be coming from ember-browserify which is having a hard time processing the file which has rest/spread (it seems)...

**Comment by Paskalouis** [comment]
@rwjblue 
Thank you for reply, it works after I remove ember-browserify dependency.
Since it is already deprecated and replaced by ember-auto-import, then it is ok to remove this.

Thank you !
