### ISSUE TITLE
Build Error (broccoli-persistent-filter:Babel): Container is falsy?

### ISSUE THREAD

**Issue by NullVoxPopuli** [babel/ember-cli-babel#350]
Yesterday this started happening.
Been trying to find out if it's a floating dep or not, so for no dice.

```
Build Error (broccoli-persistent-filter:Babel > [Babel: emberclear]) in emberclear/adapters/application.js

/home/preston/Development/NullVoxpopuli/emberclear/client/web/emberclear/emberclear/adapters/application.js: Container is falsy
```
not sure how relevant `emberclear/adapters/application.js` is, or if it just _happens_ to be the first file, but there is no mention of Container in there (cause I assume it's a build time thing?)

<details>
<summary>The Error Report from tmp:</summary>

ENV Summary:

  TIME: Fri Jun 05 2020 06:58:29 GMT-0400 (Eastern Daylight Time)
  TITLE: ember
  ARGV:
  - /home/preston/.volta/tools/image/node/14.3.0/6.14.5/bin/node
  - /home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/.bin/ember
  - exam
  - --random
  EXEC_PATH: /home/preston/.volta/tools/image/node/14.3.0/6.14.5/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /tmp/yarn--1591354679948-0.38015005790764556
  - /home/preston/Development/NullVoxpopuli/emberclear/client/web/emberclear/node_modules/.bin
  - /home/preston/.config/yarn/link/node_modules/.bin
  - /home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/.bin
  - /home/preston/.volta/tools/image/node/14.3.0/6.14.5/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /home/preston/.volta/tools/image/node/14.3.0/6.14.5/lib/node_modules/npm/bin/node-gyp-bin
  - /home/preston/.volta/tools/image/node/14.3.0/6.14.5/bin/node_modules/npm/bin/node-gyp-bin
  - /tmp/yarn--1591354679668-0.494597846856875
  - /home/preston/Development/NullVoxpopuli/emberclear/client/web/emberclear/node_modules/.bin
  - /home/preston/.config/yarn/link/node_modules/.bin
  - /home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/.bin
  - /home/preston/.yarn/bin
  - /home/preston/.volta/tools/image/node/14.3.0/6.14.5/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /home/preston/.volta/tools/image/node/14.3.0/6.14.5/lib/node_modules/npm/bin/node-gyp-bin
  - /home/preston/.volta/tools/image/node/14.3.0/6.14.5/bin/node_modules/npm/bin/node-gyp-bin
  - /home/preston/.volta/tools/image/node/14.3.0/6.14.5/bin
  - /home/preston/.volta/tools/image/yarn/1.22.4/bin
  - /home/preston/.pythons/Python-3.6.3/bin
  - /home/preston/.cargo/bin
  - /home/preston/Applications
  - /home/preston/apps/phantomjs/bin
  - /home/preston/scripts/system-utils
  - /home/preston/scripts/git
  - /home/preston/scripts/rails
  - /home/preston/scripts
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - /home/preston/.fzf/bin
  PLATFORM: linux x64
  FREEMEM: 1777565696
  TOTALMEM: 20497272832
  UPTIME: 643812
  LOADAVG: 2.05712890625,1.35546875,0.87060546875
  CPUS:
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.16.0
  - brotli: 1.0.7
  - cldr: 37.0
  - icu: 67.1
  - llhttp: 2.0.4
  - modules: 83
  - napi: 6
  - nghttp2: 1.40.0
  - node: 14.3.0
  - openssl: 1.1.1g
  - tz: 2019c
  - unicode: 13.0
  - uv: 1.37.0
  - v8: 8.1.307.31-node.33
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: ReferenceError: /home/preston/Development/NullVoxpopuli/emberclear/client/web/emberclear/emberclear/adapters/application.js: Container is falsy
    at NodePath._replaceWith (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/path/replacement.js:166:11)
    at NodePath.replaceWith (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/path/replacement.js:156:8)
    at /home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/babel-plugin-ember-modules-api-polyfill/src/index.js:173:33
    at Array.forEach (<anonymous>:null:null)
    at /home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/babel-plugin-ember-modules-api-polyfill/src/index.js:171:38
    at Array.forEach (<anonymous>:null:null)
    at PluginPass.ImportDeclaration (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/babel-plugin-ember-modules-api-polyfill/src/index.js:106:22)
    at newFn (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/index.js:84:17)
    at traverse (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/index.js:66:12)
    at transformFile (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/core/lib/transformation/index.js:107:29)
    at transformFile.next (<anonymous>:null:null)
    at run (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/core/lib/transformation/index.js:35:12)
    at run.next (<anonymous>:null:null)
    at Function.transform (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/core/lib/transform.js:27:41)
    at transform.next (<anonymous>:null:null)
    at evaluateSync (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/gensync/index.js:244:28)
    at Function.sync (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/gensync/index.js:84:14)
    at Object.transform (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/core/lib/transform.js:36:54)
    at /home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:254:26
    at initializePromise (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/rsvp/dist/rsvp.js:523:7)
    at new Promise (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/rsvp/dist/rsvp.js:1017:35)
    at transformString (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:253:12)
    at Babel.transform (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/broccoli-babel-transpiler/index.js:106:10)
    at Babel.processString (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/broccoli-babel-transpiler/index.js:137:15)
    at Promise.then.output (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:56:23)
    at initializePromise (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/rsvp/dist/rsvp.js:523:7)
    at new Promise (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/rsvp/dist/rsvp.js:1017:35)
    at /home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:55:18
    at tryCatch (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/async-disk-cache/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/async-disk-cache/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/async-disk-cache/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/async-disk-cache/node_modules/rsvp/dist/rsvp.js:2415:5)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

  - code: [undefined]
  - codeFrame: /home/preston/Development/NullVoxpopuli/emberclear/client/web/emberclear/emberclear/adapters/application.js: Container is falsy
  - errorMessage: emberclear/adapters/application.js: /home/preston/Development/NullVoxpopuli/emberclear/client/web/emberclear/emberclear/adapters/application.js: Container is falsy
        in /tmp/broccoli-184024EKLLNvxZxjFX/out-494-analyzer_ember_auto_import_analyzer
        at broccoli-persistent-filter:Babel > [Babel: emberclear] (Babel: emberclear)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: emberclear/adapters/application.js
    - line: [undefined]
    - treeDir: /tmp/broccoli-184024EKLLNvxZxjFX/out-494-analyzer_ember_auto_import_analyzer
  - message: emberclear/adapters/application.js: /home/preston/Development/NullVoxpopuli/emberclear/client/web/emberclear/emberclear/adapters/application.js: Container is falsy
        in /tmp/broccoli-184024EKLLNvxZxjFX/out-494-analyzer_ember_auto_import_analyzer
        at broccoli-persistent-filter:Babel > [Babel: emberclear] (Babel: emberclear)
  - name: Error
  - nodeAnnotation: Babel: emberclear
  - nodeName: broccoli-persistent-filter:Babel > [Babel: emberclear]
  - originalErrorMessage: /home/preston/Development/NullVoxpopuli/emberclear/client/web/emberclear/emberclear/adapters/application.js: Container is falsy
  - stack: ReferenceError: /home/preston/Development/NullVoxpopuli/emberclear/client/web/emberclear/emberclear/adapters/application.js: Container is falsy
    at NodePath._replaceWith (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/path/replacement.js:166:11)
    at NodePath.replaceWith (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/path/replacement.js:156:8)
    at /home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/babel-plugin-ember-modules-api-polyfill/src/index.js:173:33
    at Array.forEach (<anonymous>:null:null)
    at /home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/babel-plugin-ember-modules-api-polyfill/src/index.js:171:38
    at Array.forEach (<anonymous>:null:null)
    at PluginPass.ImportDeclaration (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/babel-plugin-ember-modules-api-polyfill/src/index.js:106:22)
    at newFn (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/index.js:84:17)
    at traverse (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/traverse/lib/index.js:66:12)
    at transformFile (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/core/lib/transformation/index.js:107:29)
    at transformFile.next (<anonymous>:null:null)
    at run (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/core/lib/transformation/index.js:35:12)
    at run.next (<anonymous>:null:null)
    at Function.transform (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/core/lib/transform.js:27:41)
    at transform.next (<anonymous>:null:null)
    at evaluateSync (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/gensync/index.js:244:28)
    at Function.sync (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/gensync/index.js:84:14)
    at Object.transform (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/@babel/core/lib/transform.js:36:54)
    at /home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:254:26
    at initializePromise (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/rsvp/dist/rsvp.js:523:7)
    at new Promise (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/rsvp/dist/rsvp.js:1017:35)
    at transformString (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:253:12)
    at Babel.transform (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/broccoli-babel-transpiler/index.js:106:10)
    at Babel.processString (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/broccoli-babel-transpiler/index.js:137:15)
    at Promise.then.output (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:56:23)
    at initializePromise (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/rsvp/dist/rsvp.js:523:7)
    at new Promise (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/rsvp/dist/rsvp.js:1017:35)
    at /home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:55:18
    at tryCatch (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/async-disk-cache/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/async-disk-cache/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/async-disk-cache/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/home/preston/Development/NullVoxpopuli/emberclear/client/web/node_modules/async-disk-cache/node_modules/rsvp/dist/rsvp.js:2415:5)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

</details>

**Comment by NullVoxPopuli** [comment]
Just tried running tests without `COVERAGE=true`, and my tests started running, so that means that this is relevant / maybe _caused by_ (?) ec-code-coverage? https://github.com/kategengler/ember-cli-code-coverage/issues/265

**Comment by rwjblue** [comment]
This is being tracked over in https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/issues/112. I'll leave this issue open while we work things through (to make it easier to find that issue), but lets focus the convo over there.

**Comment by rwjblue** [comment]
Fixed and included in https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/releases/tag/v3.2.2

**Comment by rwjblue** [comment]
Reopening until we have a release of ember-cli-babel that uses that version of babel-plugin-ember-modules-api-polyfill.
