### ISSUE TITLE
TypeError: babelAddon.buildBabelOptions is not a function

### ISSUE THREAD

**Issue by sahilpaudel-pe** [babel/ember-cli-babel#363]
Dependency
```
 "ember-cli": "2.18.0",
 "ember-cli-app-version": "^2.0.0",
 "ember-cli-babel": "^5.1.7",
```

when I get this error
On running `ember s`

Full stacktrace
```
- broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: babelAddon.buildBabelOptions is not a function
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: babelAddon.buildBabelOptions is not a function
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: babelAddon.buildBabelOptions is not a function
    at Package.buildBabelOptions (/Users/sahilpaudel/Documents/PharmEasy/Elixir/AfterGlow/frontend/node_modules/ember-auto-import/js/package.js:47:39)
    at new Package (/Users/sahilpaudel/Documents/PharmEasy/Elixir/AfterGlow/frontend/node_modules/ember-auto-import/js/package.js:30:46)
    at Function.lookup (/Users/sahilpaudel/Documents/PharmEasy/Elixir/AfterGlow/frontend/node_modules/ember-auto-import/js/package.js:38:35)
    at new AutoImport (/Users/sahilpaudel/Documents/PharmEasy/Elixir/AfterGlow/frontend/node_modules/ember-auto-import/js/auto-import.js:26:45)
    at Function.lookup (/Users/sahilpaudel/Documents/PharmEasy/Elixir/AfterGlow/frontend/node_modules/ember-auto-import/js/auto-import.js:39:27)
    at Class.included (/Users/sahilpaudel/Documents/PharmEasy/Elixir/AfterGlow/frontend/node_modules/ember-auto-import/js/index.js:26:48)
    at Class.superWrapper [as included] (/Users/sahilpaudel/Documents/PharmEasy/Elixir/AfterGlow/frontend/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
    at /Users/sahilpaudel/Documents/PharmEasy/Elixir/AfterGlow/frontend/node_modules/ember-cli/lib/models/addon.js:405:26
    at Array.reduce (<anonymous>)
    at Class.eachAddonInvoke (/Users/sahilpaudel/Documents/PharmEasy/Elixir/AfterGlow/frontend/node_modules/ember-cli/lib/models/addon.js:402:24)
```

Any help?

**Comment by rwjblue** [comment]
You need to update your version of ember-cli-babel in your application. 5.x is super super old and definitely unsupported. In this case you can see that ember-auto-import is attempting to call the `buildBabelOptions` public API on whatever `ember-cli-babel` version happens to be running, but it assumes that it is going to be at least 7.x.
