### ISSUE TITLE
[v7.21.0] includeExternalHelpers option breaking with latest @babel

### ISSUE THREAD

**Issue by hoIIer** [babel/ember-cli-babel#384]
I cleared node_modules and ran `npm install` with version `7.21.0` and when I run `ember serve` I get the following error:

```
Error: Could not find module @babel/runtime/helpers/initializerDefineProperty/_index.mjs imported from @babel/runtime/helpers/esm/initializerDefineProperty
    at missingModule (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-276094EuqwRsv8Chf/out-559-broccoli_merge_trees/assets/vendor/loader/loader.js:247:1)
    at findModule (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-276094EuqwRsv8Chf/out-559-broccoli_merge_trees/assets/vendor/loader/loader.js:258:1)
    at Module.findDeps (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-276094EuqwRsv8Chf/out-559-broccoli_merge_trees/assets/vendor/loader/loader.js:168:1)
    at findModule (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-276094EuqwRsv8Chf/out-559-broccoli_merge_trees/assets/vendor/loader/loader.js:262:1)
    at Module.findDeps (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-276094EuqwRsv8Chf/out-559-broccoli_merge_trees/assets/vendor/loader/loader.js:168:1)
    at findModule (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-276094EuqwRsv8Chf/out-559-broccoli_merge_trees/assets/vendor/loader/loader.js:262:1)
    at requireModule (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-276094EuqwRsv8Chf/out-559-broccoli_merge_trees/assets/vendor/loader/loader.js:24:1)
    at Class._extractDefaultExport (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-276094EuqwRsv8Chf/out-559-broccoli_merge_trees/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:445:1)
    at Class.resolveOther (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-276094EuqwRsv8Chf/out-559-broccoli_merge_trees/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:105:1)
    at Class.resolve (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-276094EuqwRsv8Chf/out-559-broccoli_merge_trees/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:168:1)
    at resolve (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-276094EuqwRsv8Chf/out-559-broccoli_merge_trees/assets/@ember/-internals/container/index.js:1223:1)
    at Registry.resolve (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-276094EuqwRsv8Chf/out-559-broccoli_merge_trees/assets/@ember/-internals/container/index.js:763:1)
    at Class.resolveRegistration (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-276094EuqwRsv8Chf/out-559-broccoli_merge_trees/assets/@ember/-internals/runtime/lib/mixins/registry_proxy.js:32:1)
    at setupSessionRestoration (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-276094EuqwRsv8Chf/out-559-broccoli_merge_trees/assets/addon-tree-output/ember-simple-auth/initializers/setup-session-restoration.js:10:1)
```
...

I tried using npm-force-resolutions and set @babel/runtime: 7.12.0 but then I get a different error when running ember server:

```
Class constructor Plugin cannot be invoked without 'new'
```

I'm not sure if something is messed up with upstream babel or otherwise? really stuck

possibly related:
https://github.com/ConnectedHomes/ember-cli-babel/pull/1
https://github.com/babel/babel/issues/12881

# Update

I figured out that removing the following previously working config clears the error and loads the app:
```
    'ember-cli-babel': {
      includeExternalHelpers: true,
    },
```

Unsure why that would suddenly break? (ember-cli-babel 7.21.0)

**Comment by Turbo87** [comment]
FWIW we're having having a similar issue with the Qonto.com apps. we're also using `includeExternalHelpers` for those.

**Comment by rwjblue** [comment]
Can one of y'all make a reproduction?

**Comment by Turbo87** [comment]
@rwjblue 

- clone https://github.com/Turbo87/crates.io/commits/external-helpers
- `yarn`
- `yarn start:live`
- visit http://localhost:4200

**Comment by rwjblue** [comment]
Thank you, will try to review the demo this afternoon and see what we can do to mitigate...

**Comment by rwjblue** [comment]
Can you test now that https://github.com/babel/babel/releases/tag/v7.13.9 is published? I _think_ https://github.com/babel/babel/pull/12919 was specifically fixing htis issue...

**Comment by burritoIand** [comment]
@rwjblue that fixed it for me! thanks

**Comment by Turbo87** [comment]
I can confirm. Works well on the crates.io codebase too 👍 

thank you @rwjblue 🤗

**Comment by Turbo87** [comment]
looks like we're still having similar issues on some other apps though:

> Could not find module `@babel/runtime/helpers/esm/arrayWithHoles.js` imported from `@babel/runtime/helpers/esm/slicedToArray`

**Comment by rwjblue** [comment]
@Turbo87 And you can confirm you only have "good" Babel runtime versions (e.g. with yarn why)?

**Comment by Turbo87** [comment]
<img width="1043" alt="Bildschirmfoto 2021-03-03 um 14 19 01" src="https://user-images.githubusercontent.com/141300/109811695-75662b00-7c2b-11eb-938f-bb930d1b37b6.png">

looks like it, yes

**Comment by rwjblue** [comment]
Basically babel is including the extension in the import paths for the helpers, and our transpilation doesn't support modules at runtime including the extension.
