### ISSUE TITLE
7.26.7 breaks an addon build

### ISSUE THREAD

**Issue by dknutsen** [babel/ember-cli-babel#424]
We've got a "shared junk" addon and this morning it started breaking during build step in all ember-try scenarios (e.g. works fine with yarn.lock in the regular test run, but breaks while running with ember-try because of `--no-lockfile`). I tracked it down to this release and pinning to 7.26.6 seems to work ok.

The error message is vague, not really sure where to start with this one:
```
  broccoli-persistent-filter:Babel > [Babel: @ember-data/record-data] [Babel: @ember-data/record-data#6431 -> applyPatches#6433] applyPatches duration: 11.41 ms {"mkdir":4,"rmdir":0,"unlink":0,"change":0,"create":11,"other":0,"processed":11,"linked":0,"handleFile":11,"processString":11,"processStringTime":35033750,"persistentCacheHit":11,"persistentCachePrime":0,"handleFileTime":68844833} +0ms
cleaning up...
  ember-cli:command An error occurred running `Build` from the `test` command. Error: Unexpected token
    at error (/Users/knutsend/workspace/art19/art19-core/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/Users/knutsend/workspace/art19/art19-core/node_modules/rollup/dist/shared/node-entry.js:9824:16)
    at tryParse (/Users/knutsend/workspace/art19/art19-core/node_modules/rollup/dist/shared/node-entry.js:9717:23)
    at Module.setSource (/Users/knutsend/workspace/art19/art19-core/node_modules/rollup/dist/shared/node-entry.js:10080:33)
    at /Users/knutsend/workspace/art19/art19-core/node_modules/rollup/dist/shared/node-entry.js:12366:20
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0) +413ms
Build Error (BroccoliRollup)

Unexpected token
```

**Comment by JoseLawrence** [comment]
When using version `7.26.7`, our application is breaking too on page load and while running the tests (please see below). On pinning down to version `7.26.6` the application is loading fine. 

On page load (with 7.26.7):  
```
Uncaught Error: Could not find module `ember-resolver` imported from `test-app/app`
    at missingModule (vendor.js:5931:11)
    at findModule (vendor.js:5942:7)
    at Module.findDeps (vendor.js:5852:24)
    at findModule (vendor.js:5946:11)
    at requireModule (vendor.js:5708:15)
    at app-boot.js:3:1
```

On running tests (with 7.26.7):
```
Building
--
| Environment: test
| building...
| cleaning up
| cleaning up...
| Build Error (SourceMapConcat)
|  
| ENOENT: no such file or directory, open '/tmp/broccoli-1912roT6sdsdHO/out-701-broccoli_debug_debug_2_vendor_js/vendor/babel-polyfill/polyfill.js'
|  
|  
| Stack Trace and Error Report: /tmp/error.dump.5bac13c3e3ddd5eafghfrgd04261e9f00.log
| npm ERR! code ELIFECYCLE
| npm ERR! errno 1
| npm ERR! Exit status 1
| npm ERR!
```

**Comment by rwjblue** [comment]
@JoseLawrence the error you pasted is #429

**Comment by rwjblue** [comment]
@dknutsen - I think the issue (assuming I've understood it) is that ember-data version is older, you need 3.28.4 (or higher) I think. Alternatively, you could force it's broccoli-rollup version to be newer via yarn resolutions.

**Comment by bertdeblock** [comment]
@dknutsen Is this issue still relevant?

**Comment by dknutsen** [comment]
Probably not. I think we used a yarn resolution and are working on updating everything anyway so you can probably close this. Thank you!

**Comment by bertdeblock** [comment]
Thanks for confirming! Going to close then for now.
