### ISSUE TITLE
Cannot set property remoteAddress of #<Socket> which has only a getter when includePolyfill true on ember-cli master

### ISSUE THREAD

**Issue by jcope2013** [babel/ember-cli-babel#60]
confirmed disabling polyfill fixes issue, Open PR on socket io (https://github.com/socketio/socket.io/pull/2136)

```

ember serve
version: 1.13.8-master-553e02953a
Cannot set property remoteAddress of #<Socket> which has only a getter
TypeError: Cannot set property remoteAddress of #<Socket> which has only a getter
    at _clone (/Users/joshuacope/test/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:16)
    at _clone (/Users/joshuacope/test/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/joshuacope/test/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/joshuacope/test/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/joshuacope/test/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/joshuacope/test/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at _clone (/Users/joshuacope/test/node_modules/ember-cli-babel/node_modules/clone/clone.js:99:18)
    at clone (/Users/joshuacope/test/node_modules/ember-cli-babel/node_modules/clone/clone.js:105:10)
    at getBabelOptions (/Users/joshuacope/test/node_modules/ember-cli-babel/index.js:68:17)
    at Object.registry.add.toTree (/Users/joshuacope/test/node_modules/ember-cli-babel/index.js:21:59)

var app = new EmberApp({
  babel: {
    includePolyfill: true
  }
});
```

**Comment by stefanpenner** [comment]
is that a vanilla app? or does this require other special configuration.

**Comment by stefanpenner** [comment]
socket.io is such a trap..

**Comment by jcope2013** [comment]
just tried it with a fresh app using ember new, same result

**Comment by stefanpenner** [comment]
So it only happens when it's from source. And not from a Tarball from npm?

If so, I'm not sure this is something we can fix on our side. When we package we patch some of the bundled deps to fix them. Issues are open, but largely it's socket.io related(via testem)

**Comment by jcope2013** [comment]
I tried with ``` "ember-cli": "git://github.com/ember-cli/ember-cli.git" ``` in my package.json also and got same issue, what is best way to get master from npm?

**Comment by stefanpenner** [comment]
> I tried with "ember-cli": "git://github.com/ember-cli/ember-cli.git" in my package.json also and got same issue, what is best way to get master from npm?

You can't, what is published to NPM is a built tarball 

During publish, these two scripts patch deps. They may be of interest: https://github.com/ember-cli/ember-cli/blob/master/bin/prepare-release#L8-L9

**Comment by stefanpenner** [comment]
I would recommend taking a look at https://github.com/babel/ember-cli-babel/blob/ea7b114f1b162d43f3c6056c204b07f70967d232/index.js#L64 as it seems strange that any sort of complex object is present in those options.

I suspect that should be fixed.

**Comment by rwjblue** [comment]
I believe this has been fixed through the various versions (this issue is fairly old) so I am closing.  Please let me know if this is still affecting folks, and I can reopen...

**Comment by jasonmit** [comment]
Just for future search context, I also hit this as part of https://github.com/gpoitch/ember-cli-less/issues/65.

The ember-cli-less addon was passing into the ember-cli `registry` object which caused the less compiler to access a getter on the `registry` object which resulted in this error.

The fix was do not pass around the `registry` to external APIs.

https://github.com/gpoitch/ember-cli-less/pull/66/commits/2f7636b75cce7ab27e88cfcdf7727ee1ccabe408
