### ISSUE TITLE
Babel es7 decorators createDecoratedClass helper fails

### ISSUE THREAD

**Issue by offirgolan** [babel/ember-cli-babel#69]
```
Error while processing route: index Cannot set property 'foo' of undefined TypeError: Cannot set property 'foo' of undefined
    at defineProperties (http://localhost:4200/assets/vendor.js:156343:31)
    at http://localhost:4200/assets/vendor.js:156348:23
    at http://localhost:4200/assets/vendor.js:156502:5
```

Failure is coming from 

``` js
defineProperties(Constructor.prototype, protoProps, protoInitializers) // protoInitializers === undefined

// ... inside defineProperties

if (descriptor.initializer !== undefined) {
  initializers[key] = descriptor;continue; // ERROR: Cannot set property 'foo' of undefined
}
```

``` js
var _createDecoratedClass = (function () {
    function defineProperties(target, descriptors, initializers) {
      for (var i = 0; i < descriptors.length; i++) {
        var descriptor = descriptors[i];var decorators = descriptor.decorators;var key = descriptor.key;delete descriptor.key;delete descriptor.decorators;descriptor.enumerable = descriptor.enumerable || false;descriptor.configurable = true;if ('value' in descriptor || descriptor.initializer) descriptor.writable = true;if (decorators) {
          for (var f = 0; f < decorators.length; f++) {
            var decorator = decorators[f];if (typeof decorator === 'function') {
              descriptor = decorator(target, key, descriptor) || descriptor;
            } else {
              throw new TypeError('The decorator for method ' + descriptor.key + ' is of the invalid type ' + typeof decorator);
            }
          }if (descriptor.initializer !== undefined) {
            initializers[key] = descriptor;continue;
          }
        }Object.defineProperty(target, key, descriptor);
      }
    }return function (Constructor, protoProps, staticProps, protoInitializers, staticInitializers) {
      if (protoProps) defineProperties(Constructor.prototype, protoProps, protoInitializers);if (staticProps) defineProperties(Constructor, staticProps, staticInitializers);return Constructor;
    };
  })();
```

Tests for this can be found here: rwjblue/ember-computed-decorators/pull/61

Seems like a Babel issue which might have been fixed in later versions. Might need to up babel-core but not too sure.

**Comment by rwjblue** [comment]
I believe this is fixed with the babel@6 updates (will continue to follow up in https://github.com/rwjblue/ember-decorators/pull/61).
