### ISSUE TITLE
.babelrc in a parent directory causes build failure

### ISSUE THREAD

**Issue by aexmachina** [babel/ember-cli-babel#92]
I have a .babelrc file in the parent folder of my ember app which causes `ember serve` to fail. If I remove this file then the build works as expected. The file has the following contents:

``` js
{
  "presets": ["es2015-node4"]
}
```

The error that is generated is as follows:

```
File: modules/ember-inflector/index.js
The Broccoli Plugin: [Babel] failed with:
ReferenceError: [BABEL] modules/ember-inflector/index.js: Unknown option: /Users/simonwade/dev/Workspace/activistic-backend/.babelrc.presets
    at Logger.error (/Users/simonwade/dev/Workspace/activistic-backend/web-donation-form/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/simonwade/dev/Workspace/activistic-backend/web-donation-form/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/Users/simonwade/dev/Workspace/activistic-backend/web-donation-form/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/simonwade/dev/Workspace/activistic-backend/web-donation-form/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/simonwade/dev/Workspace/activistic-backend/web-donation-form/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/simonwade/dev/Workspace/activistic-backend/web-donation-form/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/simonwade/dev/Workspace/activistic-backend/web-donation-form/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/simonwade/dev/Workspace/activistic-backend/web-donation-form/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Babel.transform (/Users/simonwade/dev/Workspace/activistic-backend/web-donation-form/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:105:21)
    at Babel.processString (/Users/simonwade/dev/Workspace/activistic-backend/web-donation-form/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:204:25)

The broccoli plugin was instantiated at:
    at Babel.Plugin (/Users/simonwade/dev/Workspace/activistic-backend/web-donation-form/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (/Users/simonwade/dev/Workspace/activistic-backend/web-donation-form/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/index.js:60:10)
    at new Babel (/Users/simonwade/dev/Workspace/activistic-backend/web-donation-form/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:35:10)
    at Babel (/Users/simonwade/dev/Workspace/activistic-backend/web-donation-form/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:30:12)
    at Object.registry.add.toTree (/Users/simonwade/dev/Workspace/activistic-backend/web-donation-form/node_modules/ember-cli-babel/index.js:23:52)
    at /Users/simonwade/dev/Workspace/activistic-backend/web-donation-form/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/Users/simonwade/dev/Workspace/activistic-backend/web-donation-form/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at Function.module.exports.preprocessJs (/Users/simonwade/dev/Workspace/activistic-backend/web-donation-form/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:175:10)
    at CoreObject.extend.preprocessJs (/Users/simonwade/dev/Workspace/activistic-backend/web-donation-form/node_modules/ember-cli/lib/models/addon.js:818:25)
```

**Comment by Turbo87** [comment]
this will be solved once #62 is implemented. until then the best I can recommend is not mixing Babel 5 and Babel 6 in the same project :-/

**Comment by aheuermann** [comment]
I ran into this issue as well and solved by using `ignore` in the root `.babelrc`

```json
{
  "presets": ["es2015"],
  "ignore": "frontend/*"
}
```

```
ember-cli: 2.13.1
http_parser: 2.7.0
node: 6.10.3
v8: 5.1.281.101
uv: 1.9.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: darwin x64
```

**Comment by rwjblue** [comment]
FWIW, for the ember-cli-babel@7 alpha branch I have disabled discovery from .babelrc. 

I didn't do it in the current master branch because I'm unsure if it would be a breaking change. It _seems_ like this is trolling folks more than helping them, so perhaps we should just bite the bullet and land that update in 6.x?

@stefanpenner / @turbo87 - Thoughts?

**Comment by Turbo87** [comment]
> so perhaps we should just bite the bullet and land that update in 6.x

I'd be okay with that.

**Comment by andycrum** [comment]
Hey! Any update on this? The `ignore` workaround didn't work for me, so I'm at a bit of an impasse here.

**Comment by rwjblue** [comment]
Ya, I think we can make the change to disable .babelrc / package.json config detection. Just haven't had time to do it yet. The same change is on the babel-7 branch if someone wants to cherry pick it and PR that would be great.

**Comment by chrmod** [comment]
@rwjblue setting `babelrc = false` does not solve the problem for babel 5.x

The issue is that `false` gets normalized to empty array here:
https://github.com/babel/babel/blob/a2b5d5fd2d821d447434fb316eda58d8a85fb3d2/packages/babel/src/transformation/file/options/option-manager.js#L173
so babel still try to find the config is this place: 
https://github.com/babel/babel/blob/a2b5d5fd2d821d447434fb316eda58d8a85fb3d2/packages/babel/src/transformation/file/options/option-manager.js#L181

So all versions of ember-cli that use babel 5.x are affected by this issue. 

This looks like babel bug, I will issue a bugfix PR soon.
